package za.ac.cput.factory;

/**
 * PaymentFactoryTest.java
 *
 * @author Sibusiso Kubalo
 * Student Num: 218316038
 */

import org.junit.jupiter.api.Test;
import za.ac.cput.domain.Orders;
import za.ac.cput.domain.Payments;
import za.ac.cput.domain.User;

import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.*;

class PaymentFactoryTest {

    @Test
    void testBuildPayment() {
        Orders orders = new Orders(); // You may need to properly initialize this object
        User user = new User();
        Payments payment = PaymentFactory.buildPayment(
                null, // the id is null because it's auto-generated by the database
                orders,
                user,
                500.00,
                "Credit Card",
                "Completed",
                LocalDate.of(2024, 7, 23)
        );

        assertNotNull(payment);
        assertEquals(LocalDate.of(2024, 7, 23), payment.getPaymentDate());
        assertEquals(500.00, payment.getPaymentAmount());
        assertEquals("Credit Card", payment.getPaymentMethod());
        assertEquals("Completed", payment.getPaymentStatus());
    }

    @Test
    void testBuildPaymentWithNulls() {
        Orders orders = new Orders();
        User user = new User();
        Payments payment = PaymentFactory.buildPayment(
                1L,
                orders,
                user,
                0,
                "", // Invalid payment method
                "", // Invalid payment status
                null // Invalid payment date
        );

        assertNull(payment); // Expecting null due to invalid inputs
    }
}
